Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та
виведіть його значення.

In [3]:
naturals = list(range(1, 21))

print(naturals)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
натуральними числами та виведіть його значення

In [4]:
import numpy as np

matrix = np.random.randint(1, 100, size=(3, 3))

print(matrix)

[[66 37 39]
 [44  7 54]
 [60 13 60]]


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [5]:
import numpy as np


matrix = np.random.uniform(-1, 1, size=(5, 5))

print(matrix)


[[-0.77205953 -0.79489227  0.33438719  0.88185713  0.63394395]
 [ 0.35343192 -0.21667987  0.24156035  0.02298966 -0.4953441 ]
 [-0.1886445   0.41537264  0.15595817 -0.0100048   0.18227039]
 [-0.75004043 -0.09344389 -0.02798375 -0.42982537  0.07909335]
 [ 0.03735811 -0.0227273  -0.04372314 -0.64674303  0.23970519]]


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє значення елементів.

In [6]:
import numpy as np

matrix = np.random.rand(5, 5)

average_value = np.mean(matrix)

print("Матриця:")
print(matrix)
print("Середнє значення елементів:", average_value)


Матриця:
[[0.55142111 0.71177434 0.43070152 0.63847653 0.98296967]
 [0.0796306  0.55249915 0.7577971  0.20069759 0.34617204]
 [0.87262978 0.61151947 0.05393815 0.73733125 0.90409856]
 [0.60451403 0.57427281 0.44870566 0.44263834 0.37433765]
 [0.450171   0.63460956 0.16736449 0.87167022 0.06992362]]
Середнє значення елементів: 0.5227945695838087


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та виконайте на них поелементні операції

In [7]:
import numpy as np

array1 = np.random.randint(-10, 11, size=5)
array2 = np.random.randint(-10, 11, size=5)

print("Масив 1:", array1)
print("Масив 2:", array2)

sum_result = array1 + array2
print("Результат додавання:", sum_result)

subtract_result = array1 - array2
print("Результат віднімання:", subtract_result)

multiply_result = array1 * array2
print("Результат множення:", multiply_result)

array2_nonzero = np.where(array2 == 0, 1, array2)
divide_result = array1 / array2_nonzero
print("Результат ділення:", divide_result)


Масив 1: [ -1 -10   0  -5  -2]
Масив 2: [ -6 -10  -1   5  -3]
Результат додавання: [ -7 -20  -1   0  -5]
Результат віднімання: [  5   0   1 -10   1]
Результат множення: [  6 100   0 -25   6]
Результат ділення: [ 0.16666667  1.         -0.         -1.          0.66666667]


Створіть два вектори розміром 6, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.

In [8]:
import numpy as np

vector1 = np.random.rand(6)  # Вектор 1
vector2 = np.random.rand(6)  # Вектор 2

dot_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", dot_product)


Вектор 1: [0.20356141 0.6423176  0.43662787 0.37705743 0.60564502 0.68203787]
Вектор 2: [0.13768892 0.59706267 0.47025556 0.40235326 0.56207373 0.35561041]
Скалярний добуток: 1.3515258992289845


Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та перемножте їх між собою.

In [9]:
import numpy as np

matrix1 = np.random.randint(1, 16, size=(2, 3))
matrix2 = np.random.randint(1, 16, size=(3, 2))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

result_matrix = np.dot(matrix1, matrix2)

print("Результат перемноження:")
print(result_matrix)


Матриця 1:
[[11 13  9]
 [14  8  2]]
Матриця 2:
[[ 7  5]
 [10  1]
 [ 2  5]]
Результат перемноження:
[[225 113]
 [182  88]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.


In [10]:
import numpy as np

matrix = np.random.randint(1, 13, size=(3, 3))

print("Початкова матриця:")
print(matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print(" Матриця не має оберненої матриці.")


Початкова матриця:
[[ 3  8  2]
 [11  3  4]
 [ 6 11  8]]
Обернена матриця:
[[ 0.05464481  0.1147541  -0.07103825]
 [ 0.17486339 -0.03278689 -0.0273224 ]
 [-0.28142077 -0.04098361  0.21584699]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -8 до 8 та транспонуйте її

In [11]:
import numpy as np

matrix = np.random.uniform(-8, 8, size=(4, 4))

print("Початкова матриця:")
print(matrix)

transposed_matrix = np.transpose(matrix)

print("Транспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[-5.62298457  2.34884068  3.75884264 -6.54471915]
 [ 0.56377711 -5.73391331  1.37348859 -0.68402725]
 [-2.06970308 -2.67989701  6.04867941 -5.86647866]
 [ 1.45705533  3.8163572   3.90248428 -1.4708937 ]]
Транспонована матриця:
[[-5.62298457  0.56377711 -2.06970308  1.45705533]
 [ 2.34884068 -5.73391331 -2.67989701  3.8163572 ]
 [ 3.75884264  1.37348859  6.04867941  3.90248428]
 [-6.54471915 -0.68402725 -5.86647866 -1.4708937 ]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці.

In [12]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.randint(1, 11, size=4)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

average_value = np.mean(matrix)

print("Середнє значення елементів:", average_value)


Матриця:
[[ 9  8  9  6]
 [ 4  8  6  5]
 [ 3 10 10  7]]
Вектор:
[ 4  1  7 10]
Середнє значення елементів: 7.083333333333333


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [13]:
import numpy as np

matrix = np.random.randint(1, 11, size=(2, 3))

vector = np.random.uniform(0, 1, size=3)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)

product = np.dot(matrix, vector)

print("Результат добутку матриці на вектор:")
print(product)


Матриця:
[[7 4 3]
 [5 3 8]]
Вектор:
[0.73672402 0.71453992 0.83119905]
Результат добутку матриці на вектор:
[10.50882496 12.47683223]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [14]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(3, 3))

matrix2 = np.random.randint(1, 11, size=(3, 3))

print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

difference_matrix = matrix1 - matrix2

print("Різниця між матрицями:")
print(difference_matrix)


Перша матриця:
[[ 7  3  7]
 [ 8 10  3]
 [ 6  6  1]]
Друга матриця:
[[8 8 5]
 [7 6 3]
 [1 2 7]]
Різниця між матрицями:
[[-1 -5  2]
 [ 1  4  0]
 [ 5  4 -6]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [15]:
import numpy as np

matrix1 = np.random.randint(-5, 6, size=(3, 3))

matrix2 = np.random.randint(-5, 6, size=(3, 3))

print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)

product_matrix = np.dot(matrix1, matrix2)

print("Добуток матриць:")
print(product_matrix)


Перша матриця:
[[ 0 -5  4]
 [ 1 -4  4]
 [-3  0  1]]
Друга матриця:
[[ 5  0  0]
 [-5 -3 -5]
 [ 3 -2  1]]
Добуток матриць:
[[ 37   7  29]
 [ 37   4  24]
 [-12  -2   1]]


Створіть матрицю розміром 6x6, заповніть її випадковими цілими числами в діапазоні від -50 до 50 та знайдіть суму елементів матриці.

In [16]:
import numpy as np

matrix = np.random.randint(-50, 51, size=(6, 6))

print("Матриця:")
print(matrix)

sum_elements = np.sum(matrix)

print("Сума елементів матриці:", sum_elements)


Матриця:
[[-21   2  23   6  -7  43]
 [-38 -31  35  34  50  30]
 [  7  25  31 -34  -4  44]
 [ 42  16  -6  25 -13  48]
 [-10   7  48   3  35 -28]
 [-16  10  30 -16   0  28]]
Сума елементів матриці: 398


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного рядка матриці. `





In [18]:
import numpy as np

matrix = np.random.rand(4, 4)

print("Матриця:")
print(matrix)

product_vector = np.prod(matrix, axis=1)

product_vector = product_vector.reshape(-1, 1)

print("Вектор-стовпчик з добутками рядків :")
print(product_vector)


Матриця:
[[0.88307186 0.71119738 0.05626875 0.24734764]
 [0.95043709 0.28858131 0.31271806 0.9476183 ]
 [0.03320558 0.88789252 0.23593401 0.49711357]
 [0.72324131 0.14441118 0.9288942  0.59270372]]
Вектор-стовпчик з добутками рядків :
[[0.008741  ]
 [0.08127893]
 [0.00345794]
 [0.05750266]]


 Ми вивчили, як створювати одновимірні та двовимірні масиви (вектори і матриці) у мові програмування Python за допомогою бібліотеки NumPy.

  навчилися заповнювати масиви та матриці випадковими числами в певному діапазоні за допомогою функцій NumPy, таких як np.random.randint() та np.random.rand().

 виконали різні математичні операції з масивами і матрицями, такі як додавання, віднімання, множення, знаходження суми, середнього значення, добутку елементів рядків тощо.

навчилися знаходити обернені матриці за допомогою бібліотеки NumPy.

вивчили, як виконувати різні операції з векторами і матрицями, такі як знаходження скалярного добутку, транспонування, знаходження вектора-стовпчика і багато інших.

ознайомилися з бібліотекою NumPy, яка надає потужні інструменти для обробки числових даних у Python.